name: Tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  xcodebuild:
    name: Carthage
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Create Cartfile
        run: find . -type f -name "*.json" | awk '{print "binary \"" $0 "\""}' > Cartfile
      - name: Build
        run: carthage bootstrap --use-xcframeworks